version: "3"
services:
   sql:
      build: ./sql
      volumes:
         - creepy-octo-meow-js:/var/lib/mysql
      env_file:
         - ./.env
      command: --default-authentication-plugin=mysql_native_password
   app:
      build: ./app
      depends_on:
         - node
      ports:
         - 80:80
      volumes:
         - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
         - ./app/public:/usr/share/nginx/html
   node:
      build: ./apis
      env_file:
         - .env
      ports:
         - 8080:4200
      user: "node"
      volumes:
         - ./apis/src:/home/node/app/src
         - ./apis/utils:/home/node/app/utils/
         - ./apis/tsconfig.json:/home/node/app/tsconfig.json

volumes:
   creepy-octo-meow-js: