version: "3"
services:
   sql:
      build: ./sql
      volumes:
         - creepy-octo-meow-js:/var/lib/mysql
      env_file:
         - ./.env
      command: --default-authentication-plugin=mysql_native_password
   app:
      build: ./app
      depends_on:
         - node
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /docker-volumes/creepy-octo-meow-js/etc/letsencrypt/live/octomeow.site/fullchain.pem:/etc/letsencrypt/live/octomeow.site/fullchain.pem
         - /docker-volumes/creepy-octo-meow-js/etc/letsencrypt/live/octomeow.site/privkey.pem:/etc/letsencrypt/live/octomeow.site/privkey.pem
   node:
      build: ./apis
      env_file:
         - .env
      ports:
         - 8080:4200
      user: "node"
      volumes:
         - ./apis/src:/home/node/app/src
         - ./apis/utils:/home/node/app/utils/
         - ./apis/tsconfig.json:/home/node/app/tsconfig.json
volumes:
   creepy-octo-meow-js: